### ISSUE TITLE
[Error] failed to solve: failed to read expected number of bytes: unexpected EOF

### ISSUE THREAD

**Issue by 1677883418** [dhr2333/Beancount-Trans#13]
ERROR [beancount-trans-backend 1/8] FROM docker.io/library/python:3.11.6@sha256:2a725c9721f737a2944244c98c714d24f8bcfaddd9f5c15083cbaa

**Comment by dhr2333** [comment]
我已经修改docker compose的部署方式，可以直接按照README文件进行部署。
