### ISSUE TITLE
不支持Arm平台～~~

### ISSUE THREAD

**Issue by kklod** [dhr2333/Beancount-Trans#20]
嗯，树莓派玩儿不了～～

![image](https://github.com/dhr2333/Beancount-Trans/assets/50442661/18efed85-2c1b-4d37-8fff-5de26885d759)

**Comment by dhr2333** [comment]
树莓派的支持有在计划中，但具体时间无法保证。

**Comment by dhr2333** [comment]
backend及frontend的代码均已开源，可以自己根据源代码用buildx工具进行镜像构建。
